image: alpine

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
  - apk update && apk add doxygen graphviz git
  - git config --global --add safe.directory $CI_PROJECT_DIR
  - git submodule update --init doxygen-awesome-css
  - doxygen Doxyfile
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  environment: production