# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "D:\Documents\TPS\MiniChess Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "D:\Documents\TPS\MiniChess Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Documents\TPS\MiniChess Project\CMakeFiles" "D:\Documents\TPS\MiniChess Project\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "D:\Documents\TPS\MiniChess Project\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MiniChess

# Build rule for target.
MiniChess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 MiniChess
.PHONY : MiniChess

# fast build rule for target.
MiniChess/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/build
.PHONY : MiniChess/fast

src/board.obj: src/board.cpp.obj
.PHONY : src/board.obj

# target to build an object file
src/board.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/board.cpp.obj
.PHONY : src/board.cpp.obj

src/board.i: src/board.cpp.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/game.obj: src/game.cpp.obj
.PHONY : src/game.obj

# target to build an object file
src/game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/game.cpp.obj
.PHONY : src/game.cpp.obj

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/piece.obj: src/piece.cpp.obj
.PHONY : src/piece.obj

# target to build an object file
src/piece.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/piece.cpp.obj
.PHONY : src/piece.cpp.obj

src/piece.i: src/piece.cpp.i
.PHONY : src/piece.i

# target to preprocess a source file
src/piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/piece.cpp.i
.PHONY : src/piece.cpp.i

src/piece.s: src/piece.cpp.s
.PHONY : src/piece.s

# target to generate assembly for a file
src/piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/piece.cpp.s
.PHONY : src/piece.cpp.s

src/player.obj: src/player.cpp.obj
.PHONY : src/player.obj

# target to build an object file
src/player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/player.cpp.obj
.PHONY : src/player.cpp.obj

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/position.obj: src/position.cpp.obj
.PHONY : src/position.obj

# target to build an object file
src/position.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/position.cpp.obj
.PHONY : src/position.cpp.obj

src/position.i: src/position.cpp.i
.PHONY : src/position.i

# target to preprocess a source file
src/position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/position.cpp.i
.PHONY : src/position.cpp.i

src/position.s: src/position.cpp.s
.PHONY : src/position.s

# target to generate assembly for a file
src/position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\MiniChess.dir\build.make CMakeFiles/MiniChess.dir/src/position.cpp.s
.PHONY : src/position.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... MiniChess
	@echo ... src/board.obj
	@echo ... src/board.i
	@echo ... src/board.s
	@echo ... src/game.obj
	@echo ... src/game.i
	@echo ... src/game.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/piece.obj
	@echo ... src/piece.i
	@echo ... src/piece.s
	@echo ... src/player.obj
	@echo ... src/player.i
	@echo ... src/player.s
	@echo ... src/position.obj
	@echo ... src/position.i
	@echo ... src/position.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

